"""empty message

Revision ID: 0be328e37712
Revises: e4aa8413de5f
Create Date: 2019-08-30 14:30:28.739170

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0be328e37712'
down_revision = 'e4aa8413de5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_link', sa.String(length=32), nullable=False),
    sa.Column('file_add', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_add')
    )
    op.create_index(op.f('ix_files_file_link'), 'files', ['file_link'], unique=True)
    op.create_table('isActivate_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('setmeal', sa.String(length=128), nullable=False),
    sa.Column('isActivate', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id', 'code'),
    sa.UniqueConstraint('code')
    )
    op.drop_index('code', table_name='isactivate_code')
    op.drop_table('isactivate_code')
    op.create_foreign_key(None, 'expense', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'setmeals_info', 'setmeals', ['setmeals_id'], ['id'])
    op.create_foreign_key(None, 'user_balance', 'isActivate_code', ['isActivate_code_id'], ['id'])
    op.create_foreign_key(None, 'user_info', 'user_balance', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_info', type_='foreignkey')
    op.drop_constraint(None, 'user_balance', type_='foreignkey')
    op.drop_constraint(None, 'setmeals_info', type_='foreignkey')
    op.drop_constraint(None, 'expense', type_='foreignkey')
    op.create_table('isactivate_code',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('code', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('price', mysql.FLOAT(), nullable=False),
    sa.Column('setmeal', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('isActivate', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', 'code'),
    mysql_default_charset='gbk',
    mysql_engine='MyISAM'
    )
    op.create_index('code', 'isactivate_code', ['code'], unique=True)
    op.drop_table('isActivate_code')
    op.drop_index(op.f('ix_files_file_link'), table_name='files')
    op.drop_table('files')
    # ### end Alembic commands ###
