"""empty message

Revision ID: e4aa8413de5f
Revises: 
Create Date: 2019-08-30 12:29:21.048657

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e4aa8413de5f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('setmeals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('VIP', sa.SmallInteger(), nullable=False),
    sa.Column('data', sa.SmallInteger(), nullable=False),
    sa.Column('nitu', sa.SmallInteger(), nullable=False),
    sa.Column('shetu', sa.SmallInteger(), nullable=False),
    sa.Column('qiantu', sa.SmallInteger(), nullable=False),
    sa.Column('baotu', sa.SmallInteger(), nullable=False),
    sa.Column('miyuansu', sa.SmallInteger(), nullable=False),
    sa.Column('fengyun', sa.SmallInteger(), nullable=False),
    sa.Column('huaban', sa.SmallInteger(), nullable=False),
    sa.Column('qianku', sa.SmallInteger(), nullable=False),
    sa.Column('liutu', sa.SmallInteger(), nullable=False),
    sa.Column('jiuling', sa.SmallInteger(), nullable=False),
    sa.Column('wotu', sa.SmallInteger(), nullable=False),
    sa.Column('xiongmao', sa.SmallInteger(), nullable=False),
    sa.Column('baidu', sa.SmallInteger(), nullable=False),
    sa.Column('dangtu', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=16), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('fullname', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=32), nullable=True),
    sa.Column('phone', sa.Integer(), nullable=True),
    sa.Column('info_time', sa.DateTime(), nullable=True),
    sa.Column('author', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('website',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('website', sa.String(length=8), nullable=False),
    sa.Column('type', sa.String(length=8), nullable=True),
    sa.Column('accout', sa.String(length=32), nullable=False),
    sa.Column('password', sa.String(length=32), nullable=False),
    sa.Column('sum', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_website_website'), 'website', ['website'], unique=False)
    op.create_table('expense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wangzhanname', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('link', sa.String(length=128), nullable=False),
    sa.Column('deduct', sa.SmallInteger(), nullable=False),
    sa.Column('DT', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('isActivate_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('setmeal', sa.String(length=128), nullable=False),
    sa.Column('isActivate', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id', 'code'),
    sa.UniqueConstraint('code')
    )
    op.create_table('setmeals_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wangzhanname', sa.String(length=16), nullable=False),
    sa.Column('dengji', sa.SmallInteger(), nullable=False),
    sa.Column('shangxian', sa.SmallInteger(), nullable=True),
    sa.Column('xiaxian', sa.SmallInteger(), nullable=True),
    sa.Column('daoqi', sa.DateTime(), nullable=False),
    sa.Column('zhuangtai', sa.Boolean(), nullable=False),
    sa.Column('beizhu', sa.String(length=128), nullable=True),
    sa.Column('setmeals_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['setmeals_id'], ['setmeals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_balance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nitu', sa.Integer(), nullable=False),
    sa.Column('shetu', sa.Integer(), nullable=False),
    sa.Column('qiantu', sa.Integer(), nullable=False),
    sa.Column('baotu', sa.Integer(), nullable=False),
    sa.Column('miyuansu', sa.Integer(), nullable=False),
    sa.Column('fengyun', sa.Integer(), nullable=False),
    sa.Column('huaban', sa.Integer(), nullable=False),
    sa.Column('qianku', sa.Integer(), nullable=False),
    sa.Column('liutu', sa.Integer(), nullable=False),
    sa.Column('jiuling', sa.Integer(), nullable=False),
    sa.Column('wotu', sa.Integer(), nullable=False),
    sa.Column('xiongmao', sa.Integer(), nullable=False),
    sa.Column('baidu', sa.Integer(), nullable=False),
    sa.Column('dangtu', sa.Integer(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.Column('isActivate_code_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['isActivate_code_id'], ['isActivate_code.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isActivate_code_id')
    )
    op.create_table('user_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wangzhanname', sa.String(length=16), nullable=False),
    sa.Column('dengji', sa.SmallInteger(), nullable=False),
    sa.Column('shangxian', sa.SmallInteger(), nullable=True),
    sa.Column('xiaxian', sa.SmallInteger(), nullable=True),
    sa.Column('daoqi', sa.DateTime(), nullable=False),
    sa.Column('zhuangtai', sa.Boolean(), nullable=False),
    sa.Column('beizhu', sa.String(length=200), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_balance.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('cfgnotify')
    op.add_column('user', sa.Column('name', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('register', sa.DateTime(), nullable=False))
    op.add_column('user', sa.Column('times', sa.DateTime(), nullable=False))
    op.add_column('user', sa.Column('upwd', sa.String(length=16), nullable=False))
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.create_unique_constraint(None, 'user', ['name'])
    op.drop_column('user', 'username')
    op.drop_column('user', 'phone')
    op.drop_column('user', 'password')
    op.drop_column('user', 'fullname')
    op.drop_column('user', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('fullname', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('user', sa.Column('password', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('user', sa.Column('phone', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('user', sa.Column('username', mysql.VARCHAR(length=255), nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_column('user', 'upwd')
    op.drop_column('user', 'times')
    op.drop_column('user', 'register')
    op.drop_column('user', 'name')
    op.create_table('cfgnotify',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('check_order', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('notify_type', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('notify_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('notify_number', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='gbk',
    mysql_engine='MyISAM'
    )
    op.drop_table('user_info')
    op.drop_table('user_balance')
    op.drop_table('setmeals_info')
    op.drop_table('isActivate_code')
    op.drop_table('expense')
    op.drop_index(op.f('ix_website_website'), table_name='website')
    op.drop_table('website')
    op.drop_table('user_admin')
    op.drop_table('setmeals')
    # ### end Alembic commands ###
